apiVersion: v1
kind: Service
metadata:
  name: stockapi-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: stockapi  
  ports:
  - name: http 
    port: 80  
    targetPort: 8081
  - name: https
    port: 443
    targetPort: 8081  
  type: LoadBalancer   
